markdown: rdiscount 
pygments: true

project_github:         https://github.com/FireZ-ZLF/Noah-NP2300-LBox

title_page:             Noah-NP2300-LBox by FireZ-ZLF
title_name:             Noah-NP2300-LBox
title_info:             一个诺亚舟NP2300学习机拓展工具包

download_zip:           https://github.com/FireZ-ZLF/Noah-NP2300-LBox/zipball/master
download_gz:            https://github.com/FireZ-ZLF/Noah-NP2300-LBox/tarball/master
download_pan_zip:       http://pan.baidu.com/s/1eQnCdVW
download_pan_gz:        http://pan.baidu.com/s/1jGp5KOY

version:                v2.0.2-5-g704cd2f
version_pan:            v2.0.2-5-g704cd2f
