markdown: rdiscount 
pygments: true

project_github:         https://github.com/FireZ-ZLF/Noah-NP2300-LBox

title_page:             Noah-NP2300-LBox by FireZ-ZLF
title_name:             Noah-NP2300-LBox
title_info:             一个诺亚舟NP2300学习机拓展工具包

download_zip:           https://github.com/FireZ-ZLF/Noah-NP2300-LBox/archive/v3.0.zip
download_gz:            https://github.com/FireZ-ZLF/Noah-NP2300-LBox/archive/v3.0.tar.gz

version:                v3.0
